/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact': RouteRecordInfo<
      'contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'excavator-detail': RouteRecordInfo<
      'excavator-detail',
      '/excavator/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/product-detail': RouteRecordInfo<
      '/product-detail',
      '/product-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ProductDetailContent': RouteRecordInfo<
      '/ProductDetailContent',
      '/ProductDetailContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products': RouteRecordInfo<
      '/products',
      '/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'truck-detail': RouteRecordInfo<
      'truck-detail',
      '/truck/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/views/contact.vue': {
      routes:
        | 'contact'
      views:
        | never
    }
    'src/views/excavator/[id].vue': {
      routes:
        | 'excavator-detail'
      views:
        | never
    }
    'src/views/product-detail.vue': {
      routes:
        | '/product-detail'
      views:
        | never
    }
    'src/views/ProductDetailContent.vue': {
      routes:
        | '/ProductDetailContent'
      views:
        | never
    }
    'src/views/products.vue': {
      routes:
        | '/products'
      views:
        | never
    }
    'src/views/truck/[id].vue': {
      routes:
        | 'truck-detail'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
