/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about-black': RouteRecordInfo<
      '/about-black',
      '/about-black',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact': RouteRecordInfo<
      'contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo': RouteRecordInfo<
      '/demo',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo3': RouteRecordInfo<
      '/demo3',
      '/demo3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'excavator-detail': RouteRecordInfo<
      'excavator-detail',
      '/excavator/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/index-black': RouteRecordInfo<
      '/index-black',
      '/index-black',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/product/[id]': RouteRecordInfo<
      '/product/[id]',
      '/product/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/product-detail': RouteRecordInfo<
      '/product-detail',
      '/product-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/product-detail-black': RouteRecordInfo<
      '/product-detail-black',
      '/product-detail-black',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ProductDetailContent': RouteRecordInfo<
      '/ProductDetailContent',
      '/ProductDetailContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ProductDetailContent-bak': RouteRecordInfo<
      '/ProductDetailContent-bak',
      '/ProductDetailContent-bak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products': RouteRecordInfo<
      '/products',
      '/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products-1': RouteRecordInfo<
      '/products-1',
      '/products-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products-black': RouteRecordInfo<
      '/products-black',
      '/products-black',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products-list': RouteRecordInfo<
      '/products-list',
      '/products-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/productsback': RouteRecordInfo<
      '/productsback',
      '/productsback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'truck-detail': RouteRecordInfo<
      'truck-detail',
      '/truck/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/views/about-black.vue': {
      routes:
        | '/about-black'
      views:
        | never
    }
    'src/views/contact.vue': {
      routes:
        | 'contact'
      views:
        | never
    }
    'src/views/demo.vue': {
      routes:
        | '/demo'
      views:
        | never
    }
    'src/views/demo3.vue': {
      routes:
        | '/demo3'
      views:
        | never
    }
    'src/views/excavator/[id].vue': {
      routes:
        | 'excavator-detail'
      views:
        | never
    }
    'src/views/index-black.vue': {
      routes:
        | '/index-black'
      views:
        | never
    }
    'src/views/product/[id].vue': {
      routes:
        | '/product/[id]'
      views:
        | never
    }
    'src/views/product-detail.vue': {
      routes:
        | '/product-detail'
      views:
        | never
    }
    'src/views/product-detail-black.vue': {
      routes:
        | '/product-detail-black'
      views:
        | never
    }
    'src/views/ProductDetailContent.vue': {
      routes:
        | '/ProductDetailContent'
      views:
        | never
    }
    'src/views/ProductDetailContent-bak.vue': {
      routes:
        | '/ProductDetailContent-bak'
      views:
        | never
    }
    'src/views/products.vue': {
      routes:
        | '/products'
      views:
        | never
    }
    'src/views/products-1.vue': {
      routes:
        | '/products-1'
      views:
        | never
    }
    'src/views/products-black.vue': {
      routes:
        | '/products-black'
      views:
        | never
    }
    'src/views/products-list.vue': {
      routes:
        | '/products-list'
      views:
        | never
    }
    'src/views/productsback.vue': {
      routes:
        | '/productsback'
      views:
        | never
    }
    'src/views/truck/[id].vue': {
      routes:
        | 'truck-detail'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
